version: '3.7'
services:
  web:
    container_name: web_gpb
    ports:
      - '3000:3000'
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - PERL5LIB=/app/lib
      - DB_ADMIN=admin
      - DB_ADMIN_PASS=password
      - DB_CUSTOMER=customer
      - DB_CUSTOMER_PASS=password
      - DB_HOST=psql_gpb
      - DB_PORT=5432
      - DB_NAME=message_logs
    entrypoint: ["morbo", "bin/app.pl"]
    depends_on:
      - 'db'

  db:
    image: postgres:15.3
    container_name: psql_gpb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database_gpb:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_gpb:
    driver: local